import Head from 'next/head';
import { Container, Content, MenuHeader } from './styles';
import type { Props } from './types';

export function MainLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Style-App</title>
        <meta name="Style-AppX" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Ann Jolie Lourido" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <MenuHeader links={[]} onChange={() => {}} value='' options={[]}/>
        <Content>{children}</Content>
      </Container>
    </>
  );
}
