import Head from 'next/head';
import { Container, Content } from './styles';
import Header from '@/components/Header';
import type { Props } from './types';
import { useLogic } from './logic';

export function MainLayout({ children }: Props) {
  const { products, breadcrumbs } = useLogic();
  return (
    <>
      <Head>
        <title>Mobile-App</title>
        <meta name="Mobile-App" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Ann Jolie Lourido" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Header numberOfItems={products.length} links={breadcrumbs} onChange={() => {}} value='' options={[]}/>
        <Content>{children}</Content>
      </Container>
    </>
  );
}
